# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "rtl8xxxu" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a9f9ea71-91fd-4d0a-a833-134ca0a955ba";
      fsType = "btrfs";
      options = [ "compress=lzo" "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a32aa6ae-df42-4cd4-bec1-152da716a2b9";
      fsType = "auto";
      options = [ "rw,noatime" ];
    };

  fileSystems."/media/redson" =
    { device = "/dev/disk/by-uuid/749b9d73-86a3-45b2-9b7b-aea5821f2f25";
      fsType = "btrfs";
      options = [ "defaults" "noatime" "nodev" "nofail" "user" "rw" "exec" "x-gvfs-show" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
